version: "3.6"
services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: L@bSt@ck!
  apache2:
    depends_on: 
      - mysql
    image: wordpress
    restart: always
    volumes:
      - ./apache2:/var/www/html
  armor:
    depends_on: 
      - apache2
    image: labstack/armor:0.4.5 
    restart: always
    ports:
      - 80:80
    volumes:
      - ./armor:/root/.armor
    environment:
      WORDPRESS_DB_PASSWORD: L@bSt@ck!

